https://machinelearningmastery.com/use-word-embedding-layers-deep-learning-keras/

In [14]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

In [15]:
docs = ['Well done!',
        'Good work',
        'Great effort',
        'nice work',
        'Excellent!',
        'Weak',
        'Poor effort!',
        'not good',
        'poor work',
        'Could have done better.']
# define class labels
labels = array([1,1,1,1,1,0,0,0,0,0])

In [34]:
vocab_size = 50 #maximum words in all data.
max_length = 4 #maximum words in each sentence.

# integer encode the documents
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[10, 8], [42, 7], [41, 15], [27, 7], [24], [3], [25, 15], [9, 42], [25, 7], [5, 36, 8, 23]]


In [17]:
# pad documents to a max length of 4 words
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[10  8  0  0]
 [42  7  0  0]
 [41 15  0  0]
 [27  7  0  0]
 [24  0  0  0]
 [ 3  0  0  0]
 [25 15  0  0]
 [ 9 42  0  0]
 [25  7  0  0]
 [ 5 36  8 23]]


In [24]:
#define model
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length = max_length))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [36]:
#compile model
model.compile(optimizer = 'adagrad', loss='binary_crossentropy', metrics=['acc'])

In [37]:
#model summary
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 4, 8)              400       
_________________________________________________________________
flatten_2 (Flatten)          (None, 32)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 33        
Total params: 433
Trainable params: 433
Non-trainable params: 0
_________________________________________________________________


In [38]:
#fit model
model.fit(padded_docs, labels, epochs=50, verbose=1)

Epoch 1/50
10/10 [==============================] - 0s 15ms/step - loss: 0.4116 - acc: 0.9000
Epoch 2/50
10/10 [==============================] - 0s 200us/step - loss: 0.3937 - acc: 0.9000
Epoch 3/50
10/10 [==============================] - 0s 199us/step - loss: 0.3812 - acc: 1.0000
Epoch 4/50
10/10 [==============================] - 0s 301us/step - loss: 0.3712 - acc: 1.0000
Epoch 5/50
10/10 [==============================] - 0s 400us/step - loss: 0.3626 - acc: 1.0000
Epoch 6/50
10/10 [==============================] - 0s 200us/step - loss: 0.3551 - acc: 1.0000
Epoch 7/50
10/10 [==============================] - 0s 200us/step - loss: 0.3483 - acc: 1.0000
Epoch 8/50
10/10 [==============================] - 0s 200us/step - loss: 0.3421 - acc: 1.0000
Epoch 9/50
10/10 [==============================] - 0s 400us/step - loss: 0.3364 - acc: 1.0000
Epoch 10/50
10/10 [==============================] - 0s 200us/step - loss: 0.3310 - acc: 1.0000
Epoch 11/50
10/10 [==============================]

In [39]:
# evaluate model
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
print("Accuracy {}".format(accuracy*100))

Accuracy 100.0
